// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/screenshot/screenshot.proto

package screenshot

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ScreenshotRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ScreenshotRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ScreenshotRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ScreenshotRequestMultiError, or nil if none found.
func (m *ScreenshotRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ScreenshotRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Url

	// no validation rules for Width

	// no validation rules for Height

	if len(errors) > 0 {
		return ScreenshotRequestMultiError(errors)
	}

	return nil
}

// ScreenshotRequestMultiError is an error wrapping multiple validation errors
// returned by ScreenshotRequest.ValidateAll() if the designated constraints
// aren't met.
type ScreenshotRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ScreenshotRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ScreenshotRequestMultiError) AllErrors() []error { return m }

// ScreenshotRequestValidationError is the validation error returned by
// ScreenshotRequest.Validate if the designated constraints aren't met.
type ScreenshotRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ScreenshotRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ScreenshotRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ScreenshotRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ScreenshotRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ScreenshotRequestValidationError) ErrorName() string {
	return "ScreenshotRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ScreenshotRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sScreenshotRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ScreenshotRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ScreenshotRequestValidationError{}

// Validate checks the field values on ScreenshotResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ScreenshotResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ScreenshotResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ScreenshotResponseMultiError, or nil if none found.
func (m *ScreenshotResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ScreenshotResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Data

	if len(errors) > 0 {
		return ScreenshotResponseMultiError(errors)
	}

	return nil
}

// ScreenshotResponseMultiError is an error wrapping multiple validation errors
// returned by ScreenshotResponse.ValidateAll() if the designated constraints
// aren't met.
type ScreenshotResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ScreenshotResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ScreenshotResponseMultiError) AllErrors() []error { return m }

// ScreenshotResponseValidationError is the validation error returned by
// ScreenshotResponse.Validate if the designated constraints aren't met.
type ScreenshotResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ScreenshotResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ScreenshotResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ScreenshotResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ScreenshotResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ScreenshotResponseValidationError) ErrorName() string {
	return "ScreenshotResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ScreenshotResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sScreenshotResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ScreenshotResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ScreenshotResponseValidationError{}
