// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/email/handler.proto

package email

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/2637309949/micro/v3/service/api"
	client "github.com/2637309949/micro/v3/service/client"
	server "github.com/2637309949/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Email service

func NewEmailEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Email service

type EmailService interface {
	Send(ctx context.Context, in *SendRequest, opts ...client.CallOption) (*SendResponse, error)
}

type emailService struct {
	c    client.Client
	name string
}

func NewEmailService(name string, c client.Client) EmailService {
	return &emailService{
		c:    c,
		name: name,
	}
}

func (c *emailService) Send(ctx context.Context, in *SendRequest, opts ...client.CallOption) (*SendResponse, error) {
	req := c.c.NewRequest(c.name, "Email.Send", in)
	out := new(SendResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Email service

type EmailHandler interface {
	Send(context.Context, *SendRequest, *SendResponse) error
}

func RegisterEmailHandler(s server.Server, hdlr EmailHandler, opts ...server.HandlerOption) error {
	type email interface {
		Send(ctx context.Context, in *SendRequest, out *SendResponse) error
	}
	type Email struct {
		email
	}
	h := &emailHandler{hdlr}
	return s.Handle(s.NewHandler(&Email{h}, opts...))
}

type emailHandler struct {
	EmailHandler
}

func (h *emailHandler) Send(ctx context.Context, in *SendRequest, out *SendResponse) error {
	return h.EmailHandler.Send(ctx, in, out)
}

// Api Endpoints for Spam service

func NewSpamEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Spam service

type SpamService interface {
	Classify(ctx context.Context, in *ClassifyRequest, opts ...client.CallOption) (*ClassifyResponse, error)
}

type spamService struct {
	c    client.Client
	name string
}

func NewSpamService(name string, c client.Client) SpamService {
	return &spamService{
		c:    c,
		name: name,
	}
}

func (c *spamService) Classify(ctx context.Context, in *ClassifyRequest, opts ...client.CallOption) (*ClassifyResponse, error) {
	req := c.c.NewRequest(c.name, "Spam.Classify", in)
	out := new(ClassifyResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Spam service

type SpamHandler interface {
	Classify(context.Context, *ClassifyRequest, *ClassifyResponse) error
}

func RegisterSpamHandler(s server.Server, hdlr SpamHandler, opts ...server.HandlerOption) error {
	type spam interface {
		Classify(ctx context.Context, in *ClassifyRequest, out *ClassifyResponse) error
	}
	type Spam struct {
		spam
	}
	h := &spamHandler{hdlr}
	return s.Handle(s.NewHandler(&Spam{h}, opts...))
}

type spamHandler struct {
	SpamHandler
}

func (h *spamHandler) Classify(ctx context.Context, in *ClassifyRequest, out *ClassifyResponse) error {
	return h.SpamHandler.Classify(ctx, in, out)
}
